# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3aad4f656b3932f2c56128563c5f8aa3586e037901b5947d5ca826753f42daa858d7566afca736e5d218739e53db1820baefb19d8d637a9dd558459ec78ff36

test:
  secret_key_base: 5ec740a18fc5ad540e3a98877ba7572d589e27fddf1ef7bacd888119c967309752093ed9044f00af5e4e2487c2272420e48a70db117f4a1d70bc6a63323ddba2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
